---
- name: Install httpd and execute start/stop
  hosts: webservers
  become: yes
  gather_facts: no
  tasks:
    - name: Install the latest version of httpd and restart
      ansible.builtin.yum:
        name: httpd
        state: latest
        notify: 
          - Restart Apache
    - name: Stop httpd if running
      ansible.builtin.service:
        name: httpd
        state: started
        notify: 
          - Stop Apache
      when: httpd == "started"
    - name: Display shutdown msg      
      ansible.builtin.debug:
        msg: Shutting down httpd since it is only for testing purposes
      when: httpd == "stopped"       

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: httpd
        state: restarted
    - name: Stop Apache
      ansible.builtin.service:
        name: httpd
        state: stopped
