---
- name: Create custom facts and update OS
  hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
    - name: Print out facts
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }}"
        
    - name: Check if the hostname string matches a criteria
      ansible.builtin.set_fact:
        hnm: "{{ ansible_hostname | regex_search('^CSM') }}"
        
    - name: print new var
      ansible.builtin.debug:
        msg: "{{ hnm }}"
      
    
