---
- name: Create custom facts and update OS
  hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
    - name: Print out facts
      ansible.builtin.debug:
        var: ansible_hostname
        
    - name: Print out facts
      ansible.builtin.debug:
        var: ansible_distribution_file_variety      

    - name: Print out facts
      ansible.builtin.debug:      
        var: ansible_distribution_version
